function LuttingerParams()
% This function creates the files for the Luttinger 
% parameters gamma1, gamma2, gamma3 vs. z


%% Reading the Al content in AlGaAs - generated by PH codes

xr    = load('x.r');        
z     = xr(:,1);               % z grid (the growth direction) (m^-10)
x     = xr(:,2)';               % Al alloy concentration in GaAs/AlGaAs HS

%% Masses

m0       = 9.1e-31;            % free e mass (kg)
hbar     = 1.05e-34;           % h-bar (J*sec)
m_hh     = 0.5 + 0.29*x;       % heavy holes mass (kg)
m_lh     = 0.087 + 0.063*x;    % heavy holes mass (kg)
m_hh_110 = 0.85*m_hh./m_hh;    % hh mass along <110> direction (kg)

%% Luttinger parameters for AlGaAs

coeff    = [1 -2  0;
            1  2  0;
            1  0 -2];
const    = hbar^2/(2*m0) * [1./m_hh; 1./m_lh; 1./m_hh_110];                 
gamma    = (coeff^(-1) * const)';

gamma1   = [z, gamma(:,1)];
gamma2   = [z, gamma(:,2)];
gamma3   = [z, gamma(:,3)];

%% Save the parameters to files

save 'gamma1.r' gamma1 -ascii -double
save 'gamma2.r' gamma2 -ascii -double
save 'gamma3.r' gamma3 -ascii -double